services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: news_db
      MYSQL_USER: news_user
      MYSQL_PASSWORD: news_password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
